### ISSUE TITLE
Relevant for ARM based control and update source for 0.5

### ISSUE THREAD

**Issue by waTeim** [ElOceanografo/StateSpace.jl#11] opened 2016-02-09 20:02 UTC
These [warnings](https://gist.github.com/waTeim/046b40361c9eef926c08) appear to be for the most part in other packages, but I'm starting here.  I have been searching for an appropriate Kalman filter for obtaining the most accurate GPS coordinates for navigation purposes, and this project seems like a likely candidate.  But I'm constrained to use an ARM-based processor and that means only Julia version 0.5.x.  Suggestions?

Once precompiled, this happens on every import.

    julia> import StateSpace;
    WARNING: Method definition show(Base.IO, StateSpace.FilteredState{#T<:Any, D<:Distributions.Distribution{Distributions.Multivariate, Distributions.Continuous}}) in module StateSpace at /home/jeffw/.julia/v0.5/StateSpace/src/common.jl:29 overwritten at /home/jeffw/.julia/v0.5/StateSpace/src/common.jl:38.
    WARNING: Method definition call(Type{StateSpace.AdditiveNonLinUKFSSM}, Function, Array{#T<:Any, 2}, Function, Array{#T<:Any, 2}) in module StateSpace at /home/jeffw/.julia/v0.5/StateSpace/src/UnscentedKalmanFilterAdditive.jl:11 overwritten at /home/jeffw/.julia/v0.5/StateSpace/src/UnscentedKalmanFilterAdditive.jl:19.

**Comment by JonnyCBB** [comment] 2016-02-10 12:42
@waTeim Thanks for giving us the heads up. It seems the warnings given here are due to redundant method definitions. On Julia v0.4 it doesn't flag these up but I just tried it on the v0.5 nightly build and managed to reproduce most of the warnings that you got in the Gist. (although I couldn't reproduce `WARNING: unable to determine host cpu name.`).

These warnings shouldn't prevent the package from running but we should sort them out anyway. I've made a [PR](https://github.com/ElOceanografo/StateSpace.jl/pull/12) which I hope should remove the second warning. Basically I created a constructor method that was identical to the automatically generated default constructor.

The 1st warning regarding the `show` method is a bit more tricky because the [method](https://github.com/ElOceanografo/StateSpace.jl/blob/master/src/common.jl#L37) isn't necessarily redundant but the types (according to the compiler) passed to the argument are. @ElOceanografo  can you look at this to see how you might resolve it? It may be that we have to get rid of the [type alias](https://github.com/ElOceanografo/StateSpace.jl/blob/master/src/common.jl#L26) for the `FilteredState` and the `SmoothedState` unless you have something else in mind.

**Comment by JonnyCBB** [comment] 2016-02-10 14:50
> But I'm constrained to use an ARM-based processor and that means only Julia version 0.5.x. Suggestions?

To be honest I don't know much/anything at all on this side of things. I imagine the [Julia Users Google Groups](https://groups.google.com/forum/#!forum/julia-users) is the place to ask. traffic is very high there so you're likely to get an answer very quickly.

**Comment by waTeim** [comment] 2016-02-10 15:39
Don't worry too much about the ARM comment, I mentioned it only to justify why I can't use 0.4 (it doesn't exist for ARM).  Likewise the `unable to determine host cpu name` error is a result of running it on an unidentifiable host; nothing you can do about it.

**Comment by ElOceanografo** [comment] 2016-02-14 20:03
Jonny, I just merged the PR (and added you as a collaborator so you can push directly).  We could conceivably just have a single FilteredState type, and add a boolean field saying whether or not it has been smoothed.

**Comment by waTeim** [comment] 2016-02-14 22:35
With the merge, yes, this is the only warning left.

    julia> import StateSpace;
    WARNING: Method definition show(Base.IO, StateSpace.FilteredState{#T<:Any, D<:Distributions.Distribution{Distributions.Multivariate, Distributions.Continuous}}) in module StateSpace at /home/jeffw/.julia/v0.5/StateSpace/src/common.jl:29 overwritten at /home/jeffw/.julia/v0.5/StateSpace/src/common.jl:38.

This might just silently happen in 0.4 anyway, but what I think is happening in 0.5, this is a real error though it's only being reported as a warning as the 2nd show is overwriting the 1st one and there will be only the 2nd call for either *FilteredState* or *SmoothedState*.  Not a giant problem as they are identical except for the print statement.  It should be a simple matter of confirming that the 2nd version is the only one that gets called by the print statement.  

Or put another way, you might as well make it one type because the multiple-dispatch system will not differentiate them.

    typealias SmoothedState FilteredState

    function show{T}(io::IO, fs::FilteredState{T})
            n = length(fs.state)
            dobs = size(fs.observations, 1)
            dstate = length(fs.state[1])
            println("FilteredState{$T}")
            println("$n estimates of $dstate-D process from $dobs-D observations")
            println("Log-likelihood: $(fs.loglik)")
    end

    function show{T}(io::IO, fs::SmoothedState{T})
            n = length(fs.state)
            dobs = size(fs.observations, 1)
            dstate = length(fs.state[1])
            println("SmoothedState{$T}")
            println("$n estimates of $dstate-D process from $dobs-D observations")
            println("Log-likelihood: $(fs.loglik)")
    end

**Comment by ElOceanografo** [comment] 2016-03-14 03:25
Got rid of the `SmoothedState` type as an alias for `FilteredState`.
8ce67c76c9514a2d8232d903e79448a1c01624c9
0d8363d40376c923f2780dedcb5d5c696d234245

**Closed by ElOceanografo** 2016-03-14 03:25 UTC
